export const dataMock = [
  {
    nr_albumu: 12997,
    surname: 'test',
    firstname: 'Jakub',
    email: 'test@test.pl',
    practiseMonth: 'Lipcowe',
    practiseDateRange: '01.07 - 28.07',
    company: 'Wrona',
    address: 'Klonowa',
    phone: '123456789',
    passed: false,
  },
  {
    nr_albumu: 12997,
    surname: 'aaa',
    firstname: 'Jakub2',
    email: 'test@test.pl',
    practiseMonth: 'Lipcowe',
    practiseDateRange: '01.07 - 28.07',
    company: 'Wrona',
    address: 'Klonowa',
    phone: '123456789',
    passed: false,
  },
  {
    nr_albumu: 12997,
    surname: 'b',
    firstname: 'Jakub',
    email: 'test@test.pl',
    practiseMonth: 'Lipcowe',
    practiseDateRange: '01.07 - 28.07',
    company: 'Wrona',
    address: 'Klonowa',
    phone: '123456789',
    passed: false,
  },
  {
    nr_albumu: 12997,
    surname: 'c',
    firstname: 'Jakub',
    email: 'test@test.pl',
    practiseMonth: 'Lipcowe',
    practiseDateRange: '01.07 - 28.07',
    company: 'Wrona',
    address: 'Klonowa',
    phone: '123456789',
    passed: false,
  },
  {
    nr_albumu: 12997,
    surname: 'd',
    firstname: 'Jakub',
    email: 'test@test.pl',
    practiseMonth: 'Lipcowe',
    practiseDateRange: '01.07 - 28.07',
    company: 'Wrona',
    address: 'Klonowa',
    phone: '123456789',
    passed: false,
  },
  {
    nr_albumu: 12997,
    surname: 'e',
    firstname: 'Jakub',
    email: 'test@test.pl',
    practiseMonth: 'Lipcowe',
    practiseDateRange: '01.07 - 28.07',
    company: 'Wrona',
    address: 'Klonowa',
    phone: '123456789',
    passed: false,
  },
  {
    nr_albumu: 12997,
    surname: 'f',
    firstname: 'Jakub',
    email: 'test@test.pl',
    practiseMonth: 'Lipcowe',
    practiseDateRange: '01.07 - 28.07',
    company: 'Wrona',
    address: 'Klonowa',
    phone: '123456789',
    passed: false,
  },
  {
    nr_albumu: 12997,
    surname: 'g',
    firstname: 'Jakub',
    email: 'test@test.pl',
    practiseMonth: 'Lipcowe',
    practiseDateRange: '01.07 - 28.07',
    company: 'Wrona',
    address: 'Klonowa',
    phone: '123456789',
    passed: false,
  },
  {
    nr_albumu: 12997,
    surname: 'h',
    firstname: 'Jakub',
    email: 'test@test.pl',
    practiseMonth: 'Lipcowe',
    practiseDateRange: '01.07 - 28.07',
    company: 'Wrona',
    address: 'Klonowa',
    phone: '123456789',
    passed: false,
  },
];
